
<footer class="footer">
	<div class="social">
		<a href="#">유한킴벌리 프로페셔널<br><span>카카오톡 플러스</span> 친구 추가하기</a>
	</div>
	<div class="row">
		<ul class="util">
			<li><a href="#">사이트이용약관</a></li>
			<li><a href="#" class="point">개인정보처리방침</a></li>
			<li><a href="#">사이트맵</a></li>
		</ul>

		<div class="cs">
			<div>
				<p>구입문의</p>
				<a href="tel:1588-5332" class="tel">1588-5332</a>
			</div>
			<div>
				<a href="#" class="btn-cust">구매상담</a>
			</div>
		</div>

		<div class="familysite">
			<select onchange="goFamilySite(this);">
				<option>Familysite</option>
				<option value="http://www.goldenfriends.yuhan-kimberly.co.kr/">골든프렌즈</option>
				<option value="http://www.yuhan-kimberly.co.kr/">유한킴벌리</option>
				<option value="https://www.momq.co.kr/">하기스</option>
				<option value="http://www.ykbrand.co.kr/white">화이트</option>
				<option value="http://www.ykbrand.co.kr/goodfeel">좋은느낌</option>
				<option value="http://www.ykbrand.co.kr/depend">디펜드</option>
				<option value="http://www.ykbrand.co.kr/scott">스카트</option>
				<option value="http://www.ykbrand.co.kr/mybidet">마이비데</option>
			</select>
		</div>

		<div class="addr">
			<p><span>대표자 : 최규복</span><span>사업자번호 : 120-81-11436</span></p>
			<p><span>이메일 :  official@yk-proffesional.com</span></p>
			<p><span>팩스 : 02-528-3467</span></p>
			<p><span>주소 : 서울특별시 강남구 테헤란로 504</span></p>
		</div>
	</div>
	<div class="copyr">
		<p>ⓡ/* 표는 미국 킴벌리-크라크 월드와이드의 세계적인 등록상표 및 상표입니다.</p>
		<p>ⓡ/* Trademarks of Limberly-Clark Worldwide, Inc.</p>
		<p>©2013 Kimberly-Clark Worldwide Inc.<br>All Right Reserved.</p>
	</div>
</footer>
<script type="text/javascript" src="@@webroot2/assets/js/ui.js"></script>
