
<header class="header @@headtype">
	<div class="row">
		<h1 class="logo"><a href="#"><span class="a11y">유한킴벌리 프로페셔널</span></a></h1>
		<div class="etc">
			<a href="#" class="btn_partner">파트너</a>
		</div>
		<div class="headgnb">
			<ul class="menu">
				<li><a href="#">프로페셔널</a></li>
				<li><a href="#">브랜드</a></li>
				<li><a href="#">제품</a></li>
				<li><a href="#">솔루션</a></li>
				<li><a href="#">현장혁신정보</a></li>
				<li><a href="#">고객서비스</a></li>
			</ul>
		</div>
	</div>
</header>
