
<header class="header @@headtype">
	<div class="row">
		<h1 class="logo"><a href="#"><span class="a11y">유한킴벌리 프로페셔널</span></a></h1>
		<div class="headgnb">
			<ul class="menu">
				<li><a href="#">프로페셔널</a></li>
				<li><a href="#">브랜드</a></li>
				<li><a href="#">제품</a></li>
				<li><a href="#">솔루션</a></li>
				<li><a href="#">현장혁신정보</a></li>
				<li><a href="#">고객서비스</a></li>
			</ul>
			<div class="etc">
				<a href="#" class="btn_partner">파트너</a>

				<!-- 날씨 디자인 미정 <div class="weather">
					<p>미세먼지 <span>보통</span><img src="/fo/assets/images/dummy/@weather.png" alt="미세먼지 보통" /></p>
				</div> //-->
			</div>
		</div>
		<!-- 20201005 추가 -->
		<div id="recombnrswipe" class="swiper-container reomm_bnr">
			<div class="swiper-wrapper">
				<div class="swiper-slide">
					<p class="figure"><img src="./assets/images/common/reom_bnr01.png" alt="크리넥스 센터풀 화장지"></p>
					<div class="info">
						<a href="#">
							<p>낭비없이 뽑아쓰는<br>국민절약 화장지</p>
							<p class="btn_more">크리넥스 센터풀 <i></i></p>
						</a>
					</div>
				</div>
				<div class="swiper-slide">
					<p class="figure"><img src="./assets/images/common/reom_bnr02.png" alt="크리넥스 에어셀 점보롤"></p>
					<div class="info">
						<a href="#">
							<p>막힘없이 풀리는<br>국민안심 화장지</p>
							<p class="btn_more">크리넥스 에어셀 점보롤 <i></i></p>
						</a>
					</div>
				</div>
				<div class="swiper-slide">
					<p class="figure"><img src="./assets/images/common/reom_bnr03.png" alt="크리넥스 드라이셀"></p>
					<div class="info">
						<a href="#">
							<p>건강을 지키는<br>위생습관</p>
							<p class="btn_more">크리넥스 드라이셀 <i></i></p>
						</a>
					</div>
				</div>
				<div class="swiper-slide">
					<p class="figure"><img src="./assets/images/common/reom_bnr04.png" alt="와이프올 에어포켓"></p>
					<div class="info">
						<a href="#">
							<p>와이퍼의<br>새로운 기준</p>
							<p class="btn_more">와이프올 에어포켓 <i></i></p>
						</a>
					</div>
				</div>
			</div>
				<div class="swiper-pagination"></div>
		</div>
		<!--// 20201005 추가 -->

		<div class="subgnb">
			<ul class="submenu" data-sub="1">
				<li><a href="#">사업부소개</a></li>
				<li><a href="#">파트너사 찾기</a></li>
			</ul>
			<ul class="submenu" data-sub="2">
				<li><a href="#" class="logo logo_kleenex"><span class="a11y">크리넥스</span></a></li>
				<li><a href="#" class="logo logo_scott"><span class="a11y">스카트</span></a></li>
				<li><a href="#" class="logo logo_popee"><span class="a11y">뽀삐</span></a></li>
				<li><a href="#" class="logo logo_wya"><span class="a11y">와이프올</span></a></li>
				<li><a href="#" class="logo logo_ktech"><span class="a11y">킴테크</span></a></li>
				<li><a href="#" class="logo logo_cleanguard"><span class="a11y">크린가드</span></a></li>
			</ul>
			<ul class="submenu _more" data-sub="3">
				<li><a href="#" class="ti">전용용기</a>
					<ul>
						<li><a href="#">냅킨</a></li>
						<li><a href="#">와이퍼</a></li>
						<li><a href="#">위생케어</a></li>
						<li><a href="#">핸드워시</a></li>
						<li><a href="#">화장실용 화장지</a></li>
					</ul>
				</li>
				<li><a href="#" class="ti">화장실&amp;위생</a>
					<ul>
						<li><a href="#">핸드타올</a></li>
						<li><a href="#">화장실용 화장지</a></li>
						<li><a href="#">위생케어</a></li>
						<li><a href="#">핸드워시</a></li>
						<li><a href="#">미용티슈</a></li>
						<li><a href="#">방향제</a></li>
						<li><a href="#">냅킨</a></li>
					</ul>
				</li>
				<li><a href="#" class="ti">와이핑&amp;세척</a>
					<ul>
						<li><a href="#">와이퍼</a></li>
					</ul>
				</li>
				<li><a href="#" class="ti">와이퍼</a>
					<ul>
						<li><a href="#">마스크</a></li>
						<li><a href="#">글로브</a></li>
						<li><a href="#">보호복</a></li>
						<li><a href="#">위생화</a></li>
						<li><a href="#">산업용</a></li>
					</ul>
				</li>
				<li><a href="#" class="ti">사이언티픽&amp;연구개발</a>
					<ul>
						<li><a href="#">사이언티픽 글로브</a></li>
						<li><a href="#">사이언티픽 마스크</a></li>
						<li><a href="#">사이언티픽 보호복</a></li>
						<li><a href="#">와이퍼</a></li>
						<li><a href="#">위생케어</a></li>
						<li><a href="#">핸드워시</a></li>
					</ul>
				</li>
			</ul>
			<ul class="submenu" data-sub="4">
				<li><a href="#">푸드 프로세싱&amp;서비스</a></li>
				<li><a href="#">공중화장실</a></li>
				<li><a href="#">오피스와 위생</a></li>
				<li><a href="#">크린룸</a></li>
				<li><a href="#">실험실</a></li>
				<li><a href="#">개인보호구</a></li>
			</ul>
			<ul class="submenu" data-sub="5">
				<li><a href="#">건강과 안전</a></li>
				<li><a href="#">고객경험</a></li>
				<li><a href="#">생산효율성</a></li>
				<li><a href="#">우리의 환경</a></li>
			</ul>
			<ul class="submenu" data-sub="6">
				<li><a href="#">제품구매 상담</a></li>
				<li><a href="#">고객상담</a></li>
			</ul>
		</div>

	</div>
</header>
